#!/bin/sh

HERE="$(dirname "$(readlink -f "${0}")")"
export PYTHONHOME="${HERE}/usr"
export PYTHONPATH="${HERE}/usr/lib/python3.11/site-packages"
exec "${HERE}/usr/bin/python3.11" "${HERE}/usr/src/FUCTool.py"
